version: '3'

services:
  minicert:
    build: .
    command: bash -c "./entrypoint.sh"
    environment:
      CONFIG_ENV: ${CONFIG_ENV}
    container_name: minicert
    volumes:
      - .:/var/docker/minicert
      - ./minicert/static:/static
    expose:
      - "8000"
    depends_on:
      - db
      - httpbin
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "80:80"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8001:5432"
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/docker/minicert
      - ./minicert/nginx:/etc/nginx/conf.d
      - ./minicert/static:/static
    depends_on:
      - minicert

volumes:
  postgres_data:
